socket_path: "/var/run/foff-milter.sock"
default_action:
  type: "Accept"

rules:
  - name: "Block suspicious Chinese services"
    criteria:
      type: "MailerPattern"
      pattern: "service\\..*\\.cn"
    action:
      type: "Reject"
      message: "Mail from suspicious service rejected"

  - name: "Block known spam mailers"
    criteria:
      type: "Or"
      criteria:
        - type: "MailerPattern"
          pattern: ".*spam.*"
        - type: "MailerPattern"
          pattern: ".*bulk.*"
    action:
      type: "Reject"
      message: "Bulk/spam mailer rejected"

  - name: "Tag suspicious senders"
    criteria:
      type: "SenderPattern"
      pattern: ".*@suspicious-domain\\.com"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Flag"
      header_value: "YES"

  - name: "Tag emails with suspicious subjects"
    criteria:
      type: "SubjectPattern"
      pattern: "(?i)(viagra|cialis|lottery|winner)"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Subject"
      header_value: "Suspicious content detected"

  - name: "Complex rule example"
    criteria:
      type: "And"
      criteria:
        - type: "SenderPattern"
          pattern: ".*@.*\\.cn$"
        - type: "Or"
          criteria:
            - type: "SubjectPattern"
              pattern: "(?i)urgent"
            - type: "HeaderPattern"
              header: "x-priority"
              pattern: "1"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Complex"
      header_value: "Chinese sender with urgent priority"
