# Test Configuration - Structured Approach
[system]
socket_path = "/tmp/test.sock"

[modules]
enabled = true
config_dir = "modules"

[legacy]
enabled = false
config_file = "legacy-rules.yaml"

[default_action]
type = "Accept"
