# FOFF Milter Test Configuration
[system]
socket_path = "/tmp/test.sock"

[statistics]
enabled = true
database_path = "/tmp/test-stats.db"
flush_interval_seconds = 60

[modules]
enabled = true
config_dir = "/tmp/test-modules"

[legacy]
enabled = false
config_file = "/etc/foff-milter/legacy-rules.yaml"

[default_action]
type = "Accept"
