# FOFF Milter - Comprehensive Configuration Example
# This file demonstrates all available features and criteria types

socket_path: "/var/run/foff-milter.sock"
default_action:
  type: "Accept"

rules:
  # Block emails from suspicious Chinese services (your original requirement)
  - name: "Block suspicious Chinese services"
    criteria:
      type: "MailerPattern"
      pattern: "service\\..*\\.cn"
    action:
      type: "Reject"
      message: "Mail from suspicious service rejected"

  # Block known spam mailers
  - name: "Block known spam mailers"
    criteria:
      type: "Or"
      criteria:
        - type: "MailerPattern"
          pattern: ".*spam.*"
        - type: "MailerPattern"
          pattern: ".*bulk.*"
        - type: "MailerPattern"
          pattern: ".*mass.*"
    action:
      type: "Reject"
      message: "Bulk/spam mailer rejected"

  # Block specific sender domains
  - name: "Block blacklisted domains"
    criteria:
      type: "SenderPattern"
      pattern: ".*@(spam-domain|bad-domain|malicious)\\.com$"
    action:
      type: "Reject"
      message: "Sender domain is blacklisted"

  # Tag pharmaceutical spam
  - name: "Tag pharmaceutical spam"
    criteria:
      type: "SubjectPattern"
      pattern: "(?i)(viagra|cialis|pharmacy|pills|medication)"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Pharma"
      header_value: "YES"

  # Tag financial scams
  - name: "Tag financial scams"
    criteria:
      type: "Or"
      criteria:
        - type: "SubjectPattern"
          pattern: "(?i)(lottery|winner|million|inheritance|prince)"
        - type: "SubjectPattern"
          pattern: "(?i)(urgent.*transfer|bank.*account|wire.*money)"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Financial"
      header_value: "Potential scam detected"

  # Complex rule: Suspicious foreign urgent emails
  - name: "Suspicious foreign urgent emails"
    criteria:
      type: "And"
      criteria:
        - type: "SenderPattern"
          pattern: ".*@.*\\.(cn|ru|tk|ml|ga)$"
        - type: "Or"
          criteria:
            - type: "SubjectPattern"
              pattern: "(?i)(urgent|immediate|asap|emergency)"
            - type: "HeaderPattern"
              header: "x-priority"
              pattern: "1"
            - type: "HeaderPattern"
              header: "importance"
              pattern: "(?i)high"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Suspicious"
      header_value: "Foreign urgent email"

  # Tag emails with suspicious attachments (based on content-type headers)
  - name: "Tag suspicious attachments"
    criteria:
      type: "Or"
      criteria:
        - type: "HeaderPattern"
          header: "content-type"
          pattern: "(?i)application/(zip|rar|exe|bat|scr)"
        - type: "HeaderPattern"
          header: "content-disposition"
          pattern: "(?i)filename=.*\\.(exe|bat|scr|com|pif)\"?"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Attachment"
      header_value: "Suspicious attachment type"

  # Block emails to specific recipients (honeypot addresses)
  - name: "Block honeypot recipients"
    criteria:
      type: "RecipientPattern"
      pattern: ".*(honeypot|trap|spam-trap)@.*"
    action:
      type: "Reject"
      message: "Recipient not found"

  # Tag emails with excessive recipients (potential spam)
  - name: "Tag bulk recipients"
    criteria:
      type: "HeaderPattern"
      header: "to"
      pattern: ".*,.*,.*,.*,.*"  # 5 or more recipients
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Bulk"
      header_value: "Multiple recipients detected"

  # Complex rule: Phishing attempt detection
  - name: "Detect phishing attempts"
    criteria:
      type: "And"
      criteria:
        - type: "Or"
          criteria:
            - type: "SubjectPattern"
              pattern: "(?i)(verify.*account|suspend.*account|update.*payment)"
            - type: "SubjectPattern"
              pattern: "(?i)(security.*alert|unusual.*activity|confirm.*identity)"
        - type: "Or"
          criteria:
            - type: "SenderPattern"
              pattern: ".*@(?!.*\\.(bank|paypal|amazon|microsoft|google)\\.com).*"
            - type: "HeaderPattern"
              header: "reply-to"
              pattern: ".*@(?!.*\\.(bank|paypal|amazon|microsoft|google)\\.com).*"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Phishing"
      header_value: "Potential phishing attempt"
