socket_path: "/var/run/foff-milter.sock"
default_action:
  type: "Accept"

rules:
  # Catch the exact psybook.info spam pattern
  - name: "Block young domains impersonating State Farm"
    criteria:
      type: "And"
      criteria:
        - type: "DomainAge"
          max_age_days: 365  # psybook.info is 296 days old
          check_sender: true
          use_mock_data: false  # Use REAL WHOIS lookups
        - type: "HeaderPattern"
          header: "from"
          pattern: "(?i)state\\s*farm"
    action:
      type: "Reject"
      message: "Young domain impersonating State Farm blocked"

  # General young domain detection
  - name: "Tag very young domains"
    criteria:
      type: "DomainAge"
      max_age_days: 90
      check_sender: true
      use_mock_data: false  # Use REAL WHOIS lookups
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Young-Domain"
      header_value: "Domain registered within 90 days"

  # Catch young domains with suspicious TLDs
  - name: "Block young suspicious TLD domains"
    criteria:
      type: "And"
      criteria:
        - type: "DomainAge"
          max_age_days: 180
          check_sender: true
          use_mock_data: false
        - type: "SenderPattern"
          pattern: ".*@.*\\.(tk|ml|ga|cf|pw|top|info)$"
    action:
      type: "Reject"
      message: "Young domain with suspicious TLD blocked"
