# Adult content and sexual spam detection patterns
adult_services:
  dating_scams:
    - "dating.*site"
    - "meet.*singles"
    - "lonely.*women"
    - "hot.*singles"
    - "find.*love"
    - "dating.*app"
    - "match.*maker"
    - "romance.*scam"
    - "sugar.*daddy"
    - "sugar.*baby"
    - "hookup.*site"
    - "adult.*dating"
    - "casual.*dating"
    - "affair.*site"

  adult_products:
    - "male.*enhancement"
    - "penis.*enlargement"
    - "testosterone"
    - "virility"
    - "potency"
    - "libido"
    - "viagra"
    - "cialis"
    - "erectile.*dysfunction"
    - "sexual.*performance"
    - "bedroom.*performance"
    - "stamina.*booster"
    - "manhood"
    - "member.*enlargement"

  explicit_content:
    - "adult.*entertainment"
    - "xxx.*content"
    - "porn.*site"
    - "nude.*photos"
    - "sexy.*photos"
    - "adult.*videos"
    - "webcam.*girls"
    - "live.*cam"
    - "strip.*chat"
    - "escort.*service"
    - "massage.*parlor"
    - "adult.*massage"

romance_fraud:
  emotional_manipulation:
    - "lonely.*heart"
    - "true.*love"
    - "soulmate"
    - "destiny.*brought"
    - "meant.*to.*be"
    - "love.*at.*first"
    - "perfect.*match"
    - "dream.*come.*true"
    - "forever.*yours"
    - "missing.*you"

  financial_requests:
    - "emergency.*money"
    - "help.*with.*money"
    - "financial.*assistance"
    - "send.*money"
    - "wire.*money"
    - "money.*transfer"
    - "urgent.*funds"
    - "hospital.*bills"
    - "travel.*money"
    - "visa.*fees"

content_filtering:
  suggestive_terms:
    - "naughty"
    - "kinky"
    - "steamy"
    - "sensual"
    - "intimate"
    - "passionate"
    - "seductive"
    - "tempting"
    - "provocative"
    - "alluring"

  body_parts:
    - "breast"
    - "chest"
    - "curves"
    - "figure"
    - "body.*parts"
    - "private.*parts"
    - "intimate.*areas"

sender_patterns:
  suspicious_usernames:
    - ".*sexy.*"
    - ".*hot.*"
    - ".*babe.*"
    - ".*honey.*"
    - ".*lover.*"
    - ".*angel.*"
    - ".*goddess.*"
    - ".*princess.*"
    - ".*queen.*"
    - ".*beauty.*"

legitimate_exclusions:
  medical_organizations:
    - "mayoclinic.com"
    - "webmd.com"
    - "nih.gov"
    - "plannedparenthood.org"
    - "acog.org"

  health_services:
    - "teladoc.com"
    - "mdlive.com"
    - "amwell.com"
    - "doxy.me"

  news_organizations:
    - "washingtonpost.com"
    - "nytimes.com"
    - "reuters.com"
    - "cnn.com"
    - "bbc.com"

confidence_scoring:
  explicit_content: 60
  adult_products: 50
  dating_scams: 45
  romance_fraud: 55
  suggestive_content: 25
  suspicious_usernames: 20
