# Advanced security features configuration
attachment_analysis:
  enabled: true
  max_file_size_mb: 50
  timeout_seconds: 30
  scan_types: ["pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "zip", "rar", "exe", "dll"]
  deep_inspection: true
  metadata_extraction: true
  embedded_content_scan: true
  macro_detection: true
  password_protected_scan: true
  
pdf_analysis:
  enabled: true
  javascript_detection: true
  embedded_file_extraction: true
  form_analysis: true
  suspicious_structure_detection: true
  metadata_analysis: true
  
office_document_analysis:
  enabled: true
  macro_detection: true
  external_link_detection: true
  embedded_object_scan: true
  template_injection_detection: true
  vba_code_analysis: true
  
archive_analysis:
  enabled: true
  max_extraction_depth: 3
  max_files_per_archive: 100
  nested_archive_detection: true
  suspicious_filename_detection: true
  compression_ratio_analysis: true

executable_analysis:
  enabled: true
  pe_header_analysis: true
  digital_signature_verification: true
  entropy_analysis: true
  suspicious_section_detection: true
  packer_detection: true
  
url_scanning:
  enabled: true
  real_time_scanning: true
  reputation_checking: true
  redirect_following: true
  max_redirects: 5
  timeout_seconds: 10
  phishing_detection: true
  malware_detection: true
  
url_reputation:
  enabled: true
  reputation_sources: ["virustotal", "urlvoid", "safebrowsing"]
  cache_duration_hours: 24
  min_reputation_score: 0.7
  whitelist_domains: ["microsoft.com", "google.com", "amazon.com"]
  
phishing_url_detection:
  enabled: true
  homograph_detection: true
  typosquatting_detection: true
  suspicious_tld_detection: true
  url_shortener_detection: true
  brand_impersonation_detection: true
  
image_ocr:
  enabled: true
  supported_formats: ["png", "jpg", "jpeg", "gif", "bmp", "tiff"]
  max_image_size_mb: 10
  ocr_timeout_seconds: 15
  text_extraction: true
  suspicious_text_detection: true
  qr_code_detection: true
  
behavioral_sandboxing:
  enabled: false  # Requires external sandbox
  sandbox_timeout_seconds: 120
  file_execution_analysis: true
  network_behavior_analysis: true
  registry_modification_detection: true
  file_system_changes: true
  
threat_intelligence:
  enabled: true
  hash_reputation: true
  domain_reputation: true
  ip_reputation: true
  file_signature_matching: true
  yara_rules: true
  
performance_settings:
  parallel_scanning: true
  max_concurrent_scans: 4
  scan_cache_enabled: true
  cache_size_mb: 256
  scan_queue_size: 100
  
security_policies:
  quarantine_suspicious_files: true
  block_password_protected_archives: false
  block_executable_attachments: true
  block_suspicious_urls: true
  log_all_scans: true
  
notification_settings:
  alert_on_malware: true
  alert_on_suspicious_attachment: true
  alert_on_phishing_url: true
  alert_on_ocr_threats: true
  detailed_scan_reports: true
