# Brand impersonation detection patterns and legitimate exclusions
brands:
  airlines:
    english:
      - ana
      - jal
      - united
      - delta
      - american
      - southwest
      - lufthansa
      - british
      - air.*france
      - klm
      - emirates
      - qatar
      - singapore.*airlines
      - cathay
      - virgin
      - jetblue
      - alaska.*airlines
      - spirit
      - frontier
      - ryanair
      - easyjet
      - westjet
      - air.*canada
      - qantas
      - etihad
      - turkish.*airlines
      - aeroflot
      - korean.*air
      - asiana
      - china.*eastern
      - china.*southern
      - air.*china
      - eva.*air
      - thai.*airways
      - malaysia.*airlines
      - garuda
      - philippine.*airlines
      - cebu.*pacific
      - jetstar
      - scoot
      - peach
      - vanilla.*air
      - spring.*airlines
      - lucky.*air
      - hainan.*airlines
      - xiamen.*air
      - shenzhen.*airlines
      - juneyao.*airlines
      - 9.*air
      - okay.*airways
      - jin.*air
      - eastar.*jet
      - jeju.*air
      - t.*way
      - fly.*gangwon
      - air.*busan
      - air.*seoul

  ecommerce:
    english:
      - rakuten
      - amazon
      - yahoo
      - mercari
      - zozo
      - uniqlo
      - muji
      - ebay
      - paypal
    japanese:
      decoded:
        - "楽天"  # Rakuten
        - "アマゾン"  # Amazon
        - "ヤフー"  # Yahoo
        - "メルカリ"  # Mercari
        - "ゾゾ"  # ZOZO
        - "ユニクロ"  # Uniqlo
        - "無印"  # Muji
        - "会員"  # Member
      encoded:
        - "=E6=A5=BD=E5=A4=A9"  # 楽天 (Rakuten)
        - "=E3=82=A2=E3=83=9E=E3=82=BE=E3=83=B3"  # アマゾン (Amazon)
        - "=E4=BC=9A=E5=93=A1"  # 会員 (Member)

  telecom:
    english:
      - softbank
      - docomo
      - au
      - kddi
      - ntt
    japanese:
      decoded:
        - "ソフトバンク"  # SoftBank
        - "ドコモ"  # DoCoMo
        - "エーユー"  # AU
      encoded:
        - "=E3=82=BD=E3=83=95=E3=83=88=E3=83=90=E3=83=B3=E3=82=AF"  # ソフトバンク

  financial:
    english:
      - jcb
      - visa
      - mastercard
      - amex
      - aaa
      - csaa

legitimate_domains:
  airlines:
    - "ana.co.jp"
    - "jal.com"
    - "united.com"
    - "delta.com"
    - "aa.com"
  ecommerce:
    - "amazon.com"
    - "amazon.co.jp"
    - "rakuten.com"
    - "rakuten.co.jp"
    - "ebay.com"
    - "paypal.com"
  telecom:
    - "softbank.jp"
    - "nttdocomo.co.jp"
    - "au.com"
    - "kddi.com"
  financial:
    - "jcb.co.jp"
    - "visa.com"
    - "mastercard.com"
    - "americanexpress.com"
    - "aaa.com"
    - "csaa.com"

confidence_scoring:
  brand_match: 30
  domain_mismatch: 40
  suspicious_tld: 20
  dkim_failure: 10
  japanese_encoding: 5
