name: "Brand Impersonation Protection"
enabled: true
rules:
  - name: "DocuSign phishing with suspicious domains"
    criteria:
      type: "And"
      criteria:
        - type: "Or"
          criteria:
            - type: "SubjectPattern"
              pattern: "(?i).*(docusign|document.*ready|signature.*required|sign.*document|review.*document|complete.*electronically).*"
            - type: "SenderPattern"
              pattern: "(?i).*docusign.*"
        - type: "Not"
          criteria:
            type: "SenderPattern"
            pattern: ".*@(docusign\\.com|docusign\\.net)$"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Flag"
      header_value: "YES"
  - name: "PayPal phishing from compromised educational domains"
    criteria:
      type: "And"
      criteria:
        - type: "Or"
          criteria:
            - type: "SubjectPattern"
              pattern: "(?i).*(paypal|payment.*pending|account.*suspended|verify.*account|activation.*order).*"
            - type: "SenderPattern"
              pattern: "(?i).*paypal.*"
        - type: "SenderPattern"
          pattern: ".*@.*\\.(edu|ac\\.|k12\\.).*"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Flag"
      header_value: "YES"
  - name: "AAA brand impersonation"
    criteria:
      type: "And"
      criteria:
        - type: "Or"
          criteria:
            - type: "SubjectPattern"
              pattern: "(?i).*(aaa.*car.*kit|free.*car.*emergency|aaa.*emergency).*"
            - type: "SenderPattern"
              pattern: "(?i).*aaa.*"
        - type: "Not"
          criteria:
            type: "SenderPattern"
            pattern: ".*@(aaa\\.com|csaa\\.com)$"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Flag"
      header_value: "YES"
  - name: "WeTransfer brand impersonation"
    criteria:
      type: "And"
      criteria:
        - type: "Or"
          criteria:
            - type: "SubjectPattern"
              pattern: "(?i).*(wetransfer|transfer.*expired|file.*expired|recover.*transfer).*"
            - type: "SenderPattern"
              pattern: "(?i).*wetransfer.*"
        - type: "Not"
          criteria:
            type: "SenderPattern"
            pattern: ".*@(wetransfer\\.com|we\\.tl)$"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Flag"
      header_value: "YES"
