# E-commerce and shopping scam detection patterns
fake_products:
  electronics:
    - "drone.*sale"
    - "iphone.*cheap"
    - "samsung.*discount"
    - "apple.*watch.*deal"
    - "airpods.*fake"
    - "laptop.*wholesale"
    - "gaming.*console.*deal"
    - "tablet.*clearance"
    - "smartphone.*liquidation"
    - "electronics.*warehouse"

  fashion:
    - "designer.*replica"
    - "luxury.*handbag.*cheap"
    - "nike.*wholesale"
    - "adidas.*factory"
    - "gucci.*knockoff"
    - "rolex.*replica"
    - "brand.*name.*discount"
    - "fashion.*outlet"
    - "designer.*clearance"
    - "authentic.*fake"

  health_supplements:
    - "miracle.*supplement"
    - "weight.*loss.*pill"
    - "fat.*burner.*secret"
    - "muscle.*building.*formula"
    - "anti.*aging.*serum"
    - "detox.*cleanse"
    - "metabolism.*booster"
    - "energy.*supplement"
    - "natural.*remedy"
    - "herbal.*cure"

marketplace_fraud:
  amazon_impersonation:
    - "amazon.*refund"
    - "amazon.*gift.*card"
    - "amazon.*prime.*expired"
    - "amazon.*account.*suspended"
    - "amazon.*security.*alert"
    - "amazon.*payment.*failed"
    - "amazon.*order.*confirmation"
    - "amazon.*delivery.*problem"
    - "amazon.*customer.*service"
    - "amazon.*verification"

  ebay_scams:
    - "ebay.*second.*chance"
    - "ebay.*offer.*expired"
    - "ebay.*payment.*pending"
    - "ebay.*seller.*protection"
    - "ebay.*dispute.*resolution"
    - "ebay.*account.*limited"
    - "ebay.*final.*value.*fee"
    - "ebay.*listing.*violation"

  fake_reviews:
    - "product.*review.*needed"
    - "amazon.*review.*request"
    - "5.*star.*review"
    - "honest.*review.*reward"
    - "product.*testing.*opportunity"
    - "review.*and.*keep"
    - "verified.*purchase.*review"
    - "review.*manipulation"

pressure_tactics:
  flash_sales:
    - "flash.*sale.*ends"
    - "24.*hour.*sale"
    - "midnight.*sale"
    - "flash.*deal.*expires"
    - "lightning.*deal"
    - "one.*day.*only"
    - "hourly.*deals"
    - "flash.*discount"
    - "quick.*sale"
    - "instant.*savings"

  limited_time:
    - "limited.*time.*offer"
    - "expires.*tonight"
    - "last.*chance.*sale"
    - "final.*hours"
    - "sale.*ends.*soon"
    - "limited.*quantity"
    - "while.*supplies.*last"
    - "act.*fast"
    - "don't.*miss.*out"
    - "time.*running.*out"

  fake_discounts:
    - "90%.*off"
    - "80%.*discount"
    - "70%.*savings"
    - "massive.*discount"
    - "huge.*savings"
    - "unbelievable.*price"
    - "lowest.*price.*ever"
    - "clearance.*blowout"
    - "warehouse.*liquidation"
    - "going.*out.*of.*business"

shopping_cart_abandonment:
  recovery_scams:
    - "forgot.*something"
    - "cart.*expires.*soon"
    - "complete.*your.*purchase"
    - "items.*reserved"
    - "checkout.*incomplete"
    - "payment.*not.*processed"
    - "order.*not.*completed"
    - "finish.*your.*order"

counterfeit_indicators:
  quality_claims:
    - "aaa.*quality"
    - "1:1.*replica"
    - "mirror.*quality"
    - "super.*fake"
    - "high.*quality.*copy"
    - "original.*factory"
    - "same.*factory"
    - "oem.*quality"

suspicious_pricing:
  too_good_to_be_true:
    - "\\$1.*iphone"
    - "\\$5.*laptop"
    - "\\$10.*rolex"
    - "\\$20.*designer"
    - "99%.*off"
    - "free.*plus.*shipping"
    - "pay.*only.*shipping"
    - "\\$1.*trial"

legitimate_exclusions:
  major_retailers:
    - "amazon.com"
    - "ebay.com"
    - "walmart.com"
    - "target.com"
    - "bestbuy.com"
    - "costco.com"
    - "homedepot.com"
    - "lowes.com"

  brand_websites:
    - "apple.com"
    - "samsung.com"
    - "nike.com"
    - "adidas.com"
    - "microsoft.com"
    - "sony.com"

  legitimate_marketplaces:
    - "shopify.com"
    - "etsy.com"
    - "mercari.com"
    - "poshmark.com"
    - "depop.com"

confidence_scoring:
  fake_products: 55
  marketplace_fraud: 60
  pressure_tactics: 35
  counterfeit_indicators: 50
  suspicious_pricing: 65
  shopping_cart_scams: 40
