# Financial services and banking scam detection patterns
banking_phishing:
  major_banks:
    - "chase.*bank"
    - "bank.*of.*america"
    - "wells.*fargo"
    - "citibank"
    - "us.*bank"
    - "pnc.*bank"
    - "truist"
    - "td.*bank"
    - "fifth.*third"
    - "regions.*bank"
    - "huntington.*bank"
    - "suntrust"

  credit_unions:
    - "navy.*federal"
    - "usaa"
    - "penfed"
    - "alliant.*credit"
    - "golden.*1.*credit"
    - "becu"
    - "schools.*first"
    - "america.*first.*credit"

  online_banks:
    - "ally.*bank"
    - "capital.*one.*360"
    - "marcus.*goldman"
    - "discover.*bank"
    - "synchrony.*bank"
    - "american.*express"
    - "schwab.*bank"

  payment_processors:
    - "zelle.*payment"
    - "venmo.*account"
    - "paypal.*security"
    - "cash.*app.*support"
    - "apple.*pay.*alert"
    - "google.*pay.*notice"
    - "square.*payment"

credit_loan_scams:
  credit_cards:
    - "pre.*approved.*credit"
    - "credit.*repair.*service"
    - "debt.*consolidation"
    - "credit.*score.*improvement"
    - "guaranteed.*approval"
    - "no.*credit.*check"
    - "instant.*credit.*decision"
    - "credit.*limit.*increase"

  personal_loans:
    - "guaranteed.*loan.*approval"
    - "no.*credit.*check.*loan"
    - "instant.*funding"
    - "emergency.*loan"
    - "payday.*loan.*alternative"
    - "bad.*credit.*loan"
    - "personal.*loan.*pre.*approved"

  mortgage_scams:
    - "mortgage.*refinance.*offer"
    - "rate.*reduction.*program"
    - "foreclosure.*assistance"
    - "loan.*modification"
    - "mortgage.*forgiveness"
    - "harp.*program"
    - "government.*mortgage.*help"

investment_fraud:
  stock_manipulation:
    - "hot.*stock.*tip"
    - "insider.*trading.*info"
    - "guaranteed.*stock.*returns"
    - "pump.*and.*dump"
    - "penny.*stock.*alert"
    - "stock.*market.*secret"
    - "trading.*algorithm"
    - "investment.*opportunity"

  cryptocurrency_scams:
    - "crypto.*investment.*opportunity"
    - "bitcoin.*mining.*pool"
    - "cryptocurrency.*exchange"
    - "crypto.*wallet.*recovery"
    - "blockchain.*investment"
    - "defi.*yield.*farming"
    - "nft.*investment"
    - "crypto.*trading.*bot"

  retirement_fraud:
    - "401k.*rollover.*opportunity"
    - "ira.*gold.*investment"
    - "pension.*maximization"
    - "retirement.*planning.*seminar"
    - "social.*security.*optimization"
    - "annuity.*investment"

government_impersonation:
  irs_scams:
    - "irs.*tax.*refund"
    - "irs.*audit.*notice"
    - "irs.*payment.*required"
    - "irs.*penalty.*notice"
    - "irs.*verification.*required"
    - "tax.*refund.*pending"
    - "irs.*criminal.*investigation"
    - "irs.*warrant.*issued"

  social_security:
    - "social.*security.*administration"
    - "ssa.*benefit.*suspension"
    - "social.*security.*number.*compromised"
    - "disability.*benefits.*review"
    - "medicare.*enrollment.*deadline"
    - "social.*security.*overpayment"

  treasury_scams:
    - "treasury.*department.*notice"
    - "stimulus.*payment.*pending"
    - "government.*grant.*available"
    - "treasury.*bond.*maturity"
    - "federal.*tax.*credit"

insurance_fraud:
  health_insurance:
    - "medicare.*advantage.*enrollment"
    - "health.*insurance.*marketplace"
    - "medicare.*supplement.*plan"
    - "medicaid.*eligibility.*review"
    - "cobra.*continuation.*coverage"
    - "health.*savings.*account"

  auto_insurance:
    - "auto.*insurance.*rate.*quote"
    - "car.*insurance.*claim.*settlement"
    - "vehicle.*coverage.*lapse"
    - "auto.*insurance.*refund"
    - "dmv.*insurance.*verification"

  life_insurance:
    - "life.*insurance.*policy.*review"
    - "beneficiary.*update.*required"
    - "life.*insurance.*payout"
    - "term.*life.*conversion"
    - "whole.*life.*cash.*value"

financial_urgency:
  account_threats:
    - "account.*will.*be.*closed"
    - "account.*suspension.*notice"
    - "unauthorized.*access.*detected"
    - "account.*verification.*required"
    - "payment.*method.*expired"
    - "account.*locked.*security"
    - "suspicious.*activity.*detected"
    - "account.*compromise.*alert"

  payment_demands:
    - "immediate.*payment.*required"
    - "payment.*overdue.*notice"
    - "final.*notice.*payment"
    - "payment.*failure.*consequences"
    - "wire.*transfer.*required"
    - "payment.*deadline.*today"

legitimate_exclusions:
  major_banks:
    - "chase.com"
    - "bankofamerica.com"
    - "wellsfargo.com"
    - "citi.com"
    - "usbank.com"
    - "pnc.com"
    - "truist.com"

  government_agencies:
    - "irs.gov"
    - "ssa.gov"
    - "treasury.gov"
    - "medicare.gov"
    - "healthcare.gov"

  financial_services:
    - "paypal.com"
    - "venmo.com"
    - "zelle.com"
    - "ally.com"
    - "schwab.com"
    - "fidelity.com"
    - "vanguard.com"

confidence_scoring:
  government_impersonation: 75
  investment_fraud: 70
  banking_phishing: 65
  credit_loan_scams: 60
  insurance_fraud: 55
  financial_urgency: 45
