# Health spam and medical misinformation detection patterns
patterns:
  pain_relief:
    - "sciatic.*pain"
    - "back.*pain"
    - "joint.*pain"
    - "chronic.*pain"
    - "pain.*disappeared"
    - "pain.*simply.*disappeared"
    - "eliminate.*pain"
    - "get.*rid.*pain"
    - "unbearable.*pain"
    - "stuck.*in.*bed"
    - "can't.*get.*out.*bed"
    - "couldn't.*get.*out.*bed"
    - "bedridden"
    - "bed.*bound"

  miracle_cures:
    - "yellow.*vitamin"
    - "miracle.*vitamin"
    - "secret.*vitamin"
    - "newly.*discovered.*vitamin"
    - "simple.*vitamin"
    - "overnight.*cure"
    - "overnight.*healing"
    - "suddenly.*healed"
    - "suddenly.*better"
    - "energy.*strength.*teenager"
    - "strength.*teenager"
    - "energy.*teenager"

  emotional_manipulation:
    - "something.*strange.*going.*on"
    - "entire.*family.*thrilled"
    - "we.*missed.*him.*so.*much"
    - "senior.*care.*facility"
    - "thought.*we'd.*have.*to"
    - "quality.*life.*dreamed"
    - "living.*lighter.*pain.*free"
    - "get.*rid.*torment"
    - "torment.*once.*and.*for.*all"

  medical_avoidance:
    - "didn't.*see.*doctor"
    - "no.*doctor"
    - "without.*doctor"
    - "didn't.*see.*chiropractor"
    - "no.*chiropractor"
    - "didn't.*see.*physical.*therapist"
    - "no.*physical.*therapist"
    - "doesn't.*even.*know.*what.*happened"

  respiratory:
    - "breathing.*difficulties"
    - "breathing.*problem"
    - "breathing.*issue"
    - "lung.*health"
    - "respiratory.*health"
    - "your.*lungs"
    - "lung.*function"
    - "shortness.*breath"
    - "root.*cause.*breathing"
    - "#1.*root.*cause"
    - "number.*1.*cause"
    - "top.*cause"
    - "main.*cause"
    - "primary.*cause"

  pharmaceutical:
    - "miracle.*cure"
    - "doctor.*hate"
    - "big.*pharma"
    - "pharma.*conspiracy"
    - "testosterone"
    - "male.*enhancement"
    - "weight.*loss"
    - "diet.*pill"
    - "viagra"
    - "cialis"
    - "secret.*formula"
    - "health.*breakthrough"
    - "medicare.*kit"
    - "medicare.*essentials"
    - "cvs.*medicare"
    - "free.*medicare"

  conspiracy:
    - "vaccine.*truth"
    - "medical.*expose"
    - "pharma.*files"
    - "rfk.*jr"
    - "bombshell"
    - "expose.*pharma"
    - "medical.*conspiracy"
    - "health.*truth"

  general_health:
    - "health.*secret"
    - "wellness.*secret"
    - "natural.*remedy"
    - "herbal.*remedy"
    - "ancient.*remedy"
    - "joint.*heal"
    - "joint.*repair"
    - "joint.*replacement"
    - "surgery.*alternative"
    - "without.*surgery"
    - "cancels.*surgery"
    - "cancel.*surgery"
    - "avoid.*surgery"
    - "skip.*surgery"
    - "no.*surgery.*needed"
    - "surgery.*free"
    - "heal.*joint"
    - "repair.*joint"
    - "alzheimer"
    - "dementia"
    - "brain.*health"
    - "memory.*loss"
    - "cognitive"
    - "neurological"
    - "drink.*linked"
    - "food.*linked"
    - "avoid.*this.*drink"
    - "ditch.*this.*drink"
    - "stop.*drinking"
    - "dangerous.*drink"
    - "diabetes"
    - "diabetic"
    - "blood.*sugar"
    - "a1c"
    - "insulin"
    - "reverse.*diabetes"
    - "cure.*diabetes"
    - "beat.*diabetes"
    - "type.*2.*diabetes"
    - "blood.*glucose"

legitimate_exclusions:
  medical_organizations:
    - "mayoclinic.com"
    - "webmd.com"
    - "nih.gov"
    - "cdc.gov"
    - "who.int"
    - "healthline.com"
    - "medlineplus.gov"
    - "clevelandclinic.org"
    - "hopkinsmedicine.org"

  news_organizations:
    - "washingtonpost.com"
    - "nytimes.com"
    - "reuters.com"
    - "cnn.com"
    - "bbc.com"
    - "npr.org"
    - "apnews.com"
    - "wsj.com"

  health_services:
    - "fidelity.com"
    - "healthequity.com"
    - "optumbank.com"
    - "wageworks.com"
    - "further.com"

severity_levels:
  critical:
    patterns: ["miracle.*cure", "cancer.*cure", "cure.*diabetes", "pain.*simply.*disappeared", "yellow.*vitamin"]
    confidence: 50
  high:
    patterns: ["doctor.*hate", "big.*pharma", "vaccine.*truth", "sciatic.*pain", "overnight.*cure", "didn't.*see.*doctor"]
    confidence: 40
  medium:
    patterns: ["natural.*remedy", "health.*secret", "breathing.*difficulties", "stuck.*in.*bed", "energy.*teenager"]
    confidence: 25
  low:
    patterns: ["wellness", "health.*tips", "nutrition"]
    confidence: 10
