# Phishing and scam detection patterns
financial_scams:
  cryptocurrency:
    - "bitcoin"
    - "btc"
    - "cryptocurrency"
    - "crypto.*wallet"
    - "send.*bitcoin"
    - "transfer.*bitcoin"
    - "wallet.*address"
    - "blockchain"
    - "coinbase"
    - "binance"
  
  payment_fraud:
    - "wire.*transfer"
    - "money.*transfer"
    - "payment.*sent"
    - "funds.*sent"
    - "\\$\\d+.*sent"
    - "zelle.*transfer"
    - "zelle.*payment"
    - "venmo.*payment"
    - "cashapp.*transfer"
    - "paypal.*transfer"
    - "bank.*transfer"
    - "western.*union"
  
  extortion:
    - "waiting.*payment"
    - "pay.*now"
    - "24.*hours"
    - "48.*hours"
    - "expose.*secrets"
    - "compromising.*video"
    - "embarrassing.*photos"
    - "blackmail"
    - "ransom"
    - "leaked.*photos"

reward_scams:
  emergency_kits:
    - "car.*emergency.*kit"
    - "emergency.*car.*kit"
    - "roadside.*kit"
    - "aaa.*kit"
    - "auto.*club.*kit"
    - "emergency.*kit.*reward"
  
  prizes:
    - "congratulations.*winner"
    - "you.*won"
    - "claim.*prize"
    - "lottery.*winner"
    - "reward.*expires"
    - "prize.*notification"
    - "sweepstakes.*winner"
    - "contest.*winner"
    - "jackpot"
    - "million.*dollar"

social_engineering:
  urgency:
    - "urgent.*action"
    - "immediate.*response"
    - "expires.*soon"
    - "limited.*time"
    - "act.*now"
    - "time.*sensitive"
    - "deadline.*approaching"
    - "final.*notice"
    - "last.*chance"
  
  panic:
    - "account.*suspended"
    - "verify.*now"
    - "security.*alert"
    - "suspicious.*activity"
    - "payment.*failed"
    - "unauthorized.*access"
    - "breach.*detected"
    - "fraud.*alert"
    - "locked.*account"

service_abuse:
  legitimate_services:
    - "sendgrid.net"
    - "mailchimp.com"
    - "constantcontact.com"
    - "mailgun.com"
    - "docusign.net"
    - "groups.google.com"
  
  abuse_indicators:
    - "reply.*mismatch"
    - "free.*email.*reply"
    - "brand.*impersonation"
    - "suspicious.*encoding"
    - "panic.*subject"

authentication_spoofing:
  indicators:
    - "sender.*recipient.*match"
    - "external.*source"
    - "missing.*dkim"
    - "failed.*dkim"
    - "domain.*mismatch"
    - "spoofed.*sender"

confidence_scoring:
  cryptocurrency_extortion: 60
  payment_fraud: 50
  reward_scams: 40
  social_engineering: 30
  service_abuse: 45
  authentication_spoofing: 55
