name: "Suspicious Domains"
enabled: true
rules:
  - name: "Tag suspicious TLD domains"
    criteria:
      type: "SenderPattern"
      pattern: ".*@.*\\.(tk|ml|ga|cf|top|click|download|loan|racing|review|science|work|party|date|stream|trade|bid|win|cricket|accountant|faith|men|gq|cn)$"
    action:
      type: "TagAsSpam"
      header_name: "X-Spam-Flag"
      header_value: "YES"
