# Technology and software scam detection patterns
tech_support_scams:
  microsoft_impersonation:
    - "microsoft.*support"
    - "windows.*support"
    - "office.*support"
    - "microsoft.*security"
    - "windows.*defender"
    - "microsoft.*team"
    - "windows.*error"
    - "microsoft.*technician"
    - "windows.*activation"
    - "microsoft.*license"

  apple_support:
    - "apple.*support"
    - "mac.*support"
    - "iphone.*support"
    - "icloud.*security"
    - "apple.*id.*locked"
    - "itunes.*support"
    - "apple.*technician"
    - "mac.*virus.*detected"
    - "apple.*security.*alert"

  generic_tech_support:
    - "computer.*repair"
    - "virus.*removal"
    - "system.*optimization"
    - "pc.*cleanup"
    - "registry.*repair"
    - "malware.*removal"
    - "computer.*technician"
    - "technical.*support"
    - "system.*diagnostic"
    - "performance.*boost"

  isp_impersonation:
    - "internet.*service.*provider"
    - "broadband.*support"
    - "wifi.*technical.*support"
    - "router.*configuration"
    - "internet.*connection.*issue"
    - "modem.*replacement"
    - "network.*diagnostic"

fake_software:
  antivirus_scams:
    - "mcafee.*expired"
    - "norton.*renewal"
    - "antivirus.*subscription"
    - "virus.*scan.*complete"
    - "malware.*detected"
    - "security.*threat.*found"
    - "system.*infected"
    - "trojan.*detected"
    - "spyware.*removal"
    - "firewall.*disabled"

  software_downloads:
    - "cracked.*software"
    - "keygen.*download"
    - "software.*crack"
    - "free.*software.*download"
    - "pirated.*software"
    - "nulled.*script"
    - "warez.*download"
    - "torrent.*software"

  license_fraud:
    - "microsoft.*office.*license"
    - "windows.*license.*key"
    - "adobe.*license.*cheap"
    - "software.*license.*sale"
    - "oem.*license"
    - "volume.*license"
    - "educational.*license"
    - "lifetime.*license"

  browser_hijacking:
    - "browser.*update.*required"
    - "chrome.*security.*update"
    - "firefox.*critical.*update"
    - "browser.*extension.*install"
    - "plugin.*update.*needed"
    - "flash.*player.*update"
    - "java.*update.*required"

device_hardware_scams:
  fake_electronics:
    - "iphone.*wholesale"
    - "samsung.*factory.*price"
    - "laptop.*liquidation"
    - "tablet.*clearance"
    - "smartphone.*bulk.*sale"
    - "electronics.*warehouse"
    - "refurbished.*guarantee"
    - "factory.*seconds"

  warranty_scams:
    - "extended.*warranty.*offer"
    - "device.*protection.*plan"
    - "warranty.*expiration.*notice"
    - "coverage.*renewal"
    - "protection.*plan.*upgrade"
    - "warranty.*claim.*processing"

  repair_scams:
    - "screen.*repair.*special"
    - "battery.*replacement.*deal"
    - "data.*recovery.*service"
    - "phone.*repair.*discount"
    - "laptop.*repair.*offer"
    - "tablet.*screen.*fix"

cloud_saas_scams:
  fake_cloud_services:
    - "unlimited.*cloud.*storage"
    - "free.*backup.*service"
    - "cloud.*sync.*solution"
    - "online.*storage.*deal"
    - "backup.*service.*trial"
    - "cloud.*migration.*service"

  saas_impersonation:
    - "dropbox.*storage.*full"
    - "google.*drive.*quota"
    - "onedrive.*sync.*error"
    - "icloud.*storage.*upgrade"
    - "box.*account.*suspended"
    - "mega.*download.*limit"

  subscription_scams:
    - "free.*trial.*ending"
    - "premium.*upgrade.*offer"
    - "subscription.*auto.*renewal"
    - "account.*downgrade.*notice"
    - "service.*suspension.*warning"
    - "billing.*failure.*notice"

cryptocurrency_mining:
  mining_software:
    - "bitcoin.*mining.*software"
    - "crypto.*mining.*pool"
    - "mining.*rig.*software"
    - "hashrate.*optimizer"
    - "mining.*calculator"
    - "pool.*mining.*join"

  hardware_scams:
    - "asic.*miner.*sale"
    - "gpu.*mining.*rig"
    - "mining.*hardware.*deal"
    - "antminer.*wholesale"
    - "mining.*contract.*sale"
    - "cloud.*mining.*service"

  wallet_scams:
    - "crypto.*wallet.*recovery"
    - "seed.*phrase.*backup"
    - "wallet.*synchronization"
    - "private.*key.*recovery"
    - "blockchain.*wallet.*issue"
    - "cryptocurrency.*wallet.*support"

system_alerts:
  fake_warnings:
    - "system.*compromised"
    - "virus.*detected.*immediately"
    - "security.*breach.*detected"
    - "unauthorized.*access.*attempt"
    - "system.*files.*corrupted"
    - "registry.*errors.*found"
    - "performance.*issues.*detected"
    - "memory.*optimization.*needed"

  urgency_tactics:
    - "immediate.*action.*required"
    - "system.*will.*shutdown"
    - "data.*loss.*imminent"
    - "security.*threat.*active"
    - "call.*now.*to.*fix"
    - "do.*not.*restart.*computer"
    - "contact.*support.*immediately"

legitimate_exclusions:
  tech_companies:
    - "microsoft.com"
    - "apple.com"
    - "google.com"
    - "adobe.com"
    - "norton.com"
    - "mcafee.com"
    - "symantec.com"

  cloud_providers:
    - "dropbox.com"
    - "drive.google.com"
    - "onedrive.com"
    - "icloud.com"
    - "box.com"
    - "mega.nz"

  software_vendors:
    - "autodesk.com"
    - "oracle.com"
    - "salesforce.com"
    - "zoom.us"
    - "slack.com"

confidence_scoring:
  cryptocurrency_mining: 75
  tech_support_scams: 70
  fake_software: 65
  cloud_saas_scams: 60
  device_hardware_scams: 55
  system_alerts: 50
