pub mod abuse_reporter;
pub mod advanced_security;
pub mod analytics;
pub mod anonymize;
pub mod attachment_analyzer;
pub mod business_context;
pub mod config;
pub mod config_loader;
pub mod config_test;
pub mod detection;
pub mod domain_age;
pub mod domain_utils;
pub mod features;
pub mod filter;
pub mod google_groups_unsubscriber;
pub mod heuristic_config;
pub mod integration;
pub mod invoice_analyzer;
pub mod language;
pub mod machine_learning;
pub mod media_analyzer;
pub mod milter;
pub mod normalization;
pub mod performance;
pub mod seasonal_behavioral;
pub mod statistics;
pub mod toml_config;
pub mod trust_analyzer;
pub mod url_resolver;

// Re-export Config and related types for backward compatibility
pub use filter::{FilterEngine, MailContext};
pub use heuristic_config::{Action, Config, Criteria, FilterRule};
pub use language::LanguageDetector;
pub use milter::Milter;
pub use statistics::{StatEvent, StatisticsCollector};
