pub mod anonymize;
pub mod attachment_analyzer;
pub mod builtin_rules;
pub mod business_context;
pub mod config;
pub mod config_loader;
pub mod dkim_verification;
pub mod domain_age;
pub mod domain_registry;
pub mod domain_utils;
pub mod features;
pub mod filter;
pub mod google_groups_unsubscriber;
pub mod heuristic_config;
pub mod invoice_analyzer;
pub mod language;
pub mod media_analyzer;
pub mod milter;
pub mod normalization;
pub mod seasonal_behavioral;
pub mod statistics;
pub mod toml_config;
pub mod trust_analyzer;
pub mod url_resolver;
pub mod version;

// Re-export Config and related types for backward compatibility
pub use filter::{FilterEngine, MailContext};
pub use heuristic_config::{Action, Config, Criteria, FilterRule};
pub use language::LanguageDetector;
pub use milter::Milter;
pub use statistics::{StatEvent, StatisticsCollector};
